<?php

namespace Container4UfaLUU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FTIYgTVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FTIYgTV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FTIYgTV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cat' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'client' => ['privates', 'App\\Repository\\ClientRepository', 'getClientRepositoryService', true],
            'user' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'cat' => 'App\\Repository\\CategorieRepository',
            'client' => 'App\\Repository\\ClientRepository',
            'user' => 'App\\Repository\\UserRepository',
        ]);
    }
}
