<?php

namespace Container4UfaLUU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_5fl3Q4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.5fl3Q4_' shared service.
     *
     * @return \App\Controller\RubriqueRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\ProduitController::show()": the $cat argument is type-hinted with the non-existent class or interface: "App\\Controller\\RubriqueRepository". Did you forget to add a use statement?');
    }
}
