<?php

namespace Container4UfaLUU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y7kcte8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y7kcte8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.y7kcte8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cat' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'id' => ['privates', '.errored..service_locator.y7kcte8.App\\Entity\\Produit', NULL, 'Cannot autowire service ".service_locator.y7kcte8": it references class "App\\Entity\\Produit" but no such service exists.'],
        ], [
            'cat' => 'App\\Repository\\CategorieRepository',
            'entityManager' => '?',
            'id' => 'App\\Entity\\Produit',
        ]);
    }
}
