<?php

namespace Container4UfaLUU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HnwsMzPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hnwsMzP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hnwsMzP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cli' => ['privates', 'App\\Repository\\ClientRepository', 'getClientRepositoryService', true],
            'commande' => ['privates', '.errored..service_locator.hnwsMzP.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.hnwsMzP": it references class "App\\Entity\\Commande" but no such service exists.'],
            'knpSnappyPdf' => ['services', 'knp_snappy.pdf', 'getKnpSnappy_PdfService', true],
        ], [
            'cli' => 'App\\Repository\\ClientRepository',
            'commande' => 'App\\Entity\\Commande',
            'knpSnappyPdf' => '?',
        ]);
    }
}
