<?php

namespace Container4UfaLUU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9TuYU95Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9TuYU95' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9TuYU95'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'catrepo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'repo' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'catrepo' => 'App\\Repository\\CategorieRepository',
            'repo' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
