<?php

namespace Container4UfaLUU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S4p9cTFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S4p9cTF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S4p9cTF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'produit' => ['privates', '.errored..service_locator.S4p9cTF.App\\Entity\\Produit', NULL, 'Cannot autowire service ".service_locator.S4p9cTF": it references class "App\\Entity\\Produit" but no such service exists.'],
        ], [
            'manager' => '?',
            'produit' => 'App\\Entity\\Produit',
        ]);
    }
}
