<?php

namespace Container4UfaLUU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSousCategorie2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bGahbSz.App\Entity\SousCategorie' shared service.
     *
     * @return \App\Entity\SousCategorie
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.bGahbSz": it references class "App\\Entity\\SousCategorie" but no such service exists.');
    }
}
