<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFHOPQoI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFHOPQoI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFHOPQoI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFHOPQoI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFHOPQoI\App_KernelDevDebugContainer([
    'container.build_hash' => 'FHOPQoI',
    'container.build_id' => '77243262',
    'container.build_time' => 1660243840,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFHOPQoI');
