<?php

namespace ContainerFHOPQoI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FHnzvqNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FHnzvqN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FHnzvqN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'com' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
        ], [
            'com' => 'App\\Repository\\CommandeRepository',
        ]);
    }
}
