<?php

namespace ContainerFHOPQoI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SqVjb8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Sq_vjb8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Sq_vjb8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'souscategorie' => ['privates', '.errored..service_locator.Sq_vjb8.App\\Entity\\SousCategorie', NULL, 'Cannot autowire service ".service_locator.Sq_vjb8": it references class "App\\Entity\\SousCategorie" but no such service exists.'],
        ], [
            'manager' => '?',
            'souscategorie' => 'App\\Entity\\SousCategorie',
        ]);
    }
}
