<?php

namespace ContainerFHOPQoI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LK7hLDTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lK7hLDT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lK7hLDT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cat' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'produit' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'cat' => 'App\\Repository\\CategorieRepository',
            'produit' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
