<?php

namespace ContainerFHOPQoI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TU6gKrjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TU6gKrj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TU6gKrj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sousCategorie' => ['privates', '.errored..service_locator.TU6gKrj.App\\Entity\\SousCategorie', NULL, 'Cannot autowire service ".service_locator.TU6gKrj": it references class "App\\Entity\\SousCategorie" but no such service exists.'],
        ], [
            'sousCategorie' => 'App\\Entity\\SousCategorie',
        ]);
    }
}
