<?php

namespace ContainerFHOPQoI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduit3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ZJzZ1Z2.App\Entity\Produit' shared service.
     *
     * @return \App\Entity\Produit
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ZJzZ1Z2": it references class "App\\Entity\\Produit" but no such service exists.');
    }
}
